### ISSUE TITLE
global dependency `coffee-script`

### ISSUE THREAD

**Issue by 59naga** [59naga/pierrot#1]
``` bash
pierrot vhost
# ┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬────────┬──────────┐
# │ App name │ id │ mode │ pid │ status  │ restart │ uptime │ memory │ watching │
# ├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼────────┼──────────┤
# │ VHOST    │ 0  │ fork │ N/A │ errored │ 0       │ 0      │ 0 B    │ disabled │
# └──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴────────┴──────────┘

pm2 logs
# ...
# Error: spawn coffee ENOENT
# ...
```

**Comment by 59naga** [comment]
`pierrot` will no longer dependent to `cofffe-scirpt`.
It obliged to specify any compiler to yml. (eg. `interpreter: 'babel-node'`)
In the next version.

``` yml
apps:
  backup: {}

  img2svg:
    repo: https://github.com/59naga/img2svg.git
    from: img2svg.berabou.me
    to: 59816
    interpreter: 'babel-node'
```

Current situation, please `npm install coffee-script --global`.
https://github.com/59naga/pierrot/commit/8ca395922ceff4726211696b87ce6c1481e750a5
